# UniFFI's generated Kotlin bindings use JNA to invoke the Rust library.  JNA
# discovers structures and callback methods at runtime, so retain its API and
# the generated binding package while allowing the rest of the app to shrink.
-keep class com.sun.jna.** { *; }
-keep class com.torchledger.agent.rust.** { *; }

# Optional annotation metadata from Tink and desktop-only AWT paths in JNA are
# not packaged on Android. These are the missing-class rules generated by R8.
-dontwarn com.google.errorprone.annotations.CanIgnoreReturnValue
-dontwarn com.google.errorprone.annotations.CheckReturnValue
-dontwarn com.google.errorprone.annotations.Immutable
-dontwarn com.google.errorprone.annotations.RestrictedApi
-dontwarn java.awt.Component
-dontwarn java.awt.GraphicsEnvironment
-dontwarn java.awt.HeadlessException
-dontwarn java.awt.Window
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.concurrent.GuardedBy
